### ISSUE TITLE
删除怎么没有error 回调函数啊？

### ISSUE THREAD

**Issue by jiangjianshuang** [verybigorange/idb-js#6]
/**
   * @method 删除数据
   * @param {Object}
   *   @property {String} tableName 表名
   *   @property {Function} condition 查询的条件，遍历，与filter类似
   *      @arg {Object} 每个元素
   *      @return 条件
   *   @property {Function} [success] 删除成功的回调  @return {Array} 返回被删除的值
   *   @property {Function} [error] 错误函数 @return {String}
   * */
  delete({ tableName, condition, success = () => {} }) {

**Comment by verybigorange** [comment]
应该是当时写漏掉了，我发布了2.0版本，通过promise来实现的，可以修复这个问题
