### ISSUE TITLE
严重的大数据查询性能问题

### ISSUE THREAD

**Issue by htank-wang** [verybigorange/idb-js#7]
在本地测试了下10000条数据查询耗时8-9s左右。
而通过indexedDB的store.getAll()，拿出数据后在内存里for循环判断条件。耗时1s左右
demo代码如下：
![image](https://user-images.githubusercontent.com/17918845/98914117-3b99d900-2503-11eb-8cba-3d731f505d44.png)
遍历游标的方式应该是不可取的。

**Comment by verybigorange** [comment]
感谢您的建议，我准备在2.0版本去优化这些东西
